### ISSUE TITLE
Bulk Enrollment 3.4,Users are Enrolled as teacher role

### ISSUE THREAD

**Issue by MaimaKhan** [moodleuulm/moodle-local_bulkenrol#12]
This plugin was working fine but now when Teacher Enrolls Students with this Plugin after pasting Email addresses, and Enroll users. All users come up with Teacher Role.
Our default Registration is set to Student.
This happens when User is Unenrolled and then Bulk Enrollment Plugin we use the user's role comes with Teacher.
Our Moodle version is 3.4,but also checked in local 3.8 same problem comes.

**Comment by abias** [comment]
Hi @MaimaKhan ,

in the latest master branch of this plugin, an admin setting to control the role to be used for bulk enrolment was added. Up to then, the default role of the configured enrolment method was used.

Please check if the problem which you were reporting also exists in this latest master branch version.

If yes, please provided steps to reproduce (see https://docs.moodle.org/38/en/How_to_add_steps_to_reproduce_to_a_bug_report) on a vanilla Moodle 3.8 installation.

**Comment by MaimaKhan** [comment]
Actually something happened which I can't understand,  in few courses this is working fine. And in Few courses this is Enrolling users as Teachers.
And I will Reinstall this Plugin and if still exost will report it back. Thanks for Help

**Comment by abias** [comment]
So I will close this issue then.
