### ISSUE TITLE
Teacher/Faculty cannot see bulk enrolment method

### ISSUE THREAD

**Issue by rfestuartjr** [moodleuulm/moodle-local_bulkenrol#15]
Hi.

We would like to ask for help on what we need to do so that our teachers/faculty can use the bulk enrolment.  We installed v3.8-r2 (2020051200) however the teachers/faculty cannot see bulk enrolment method.

![image](https://user-images.githubusercontent.com/66813508/84872015-e2dd2600-b0b3-11ea-9427-16c2a44006d6.png)

I found two settings for "User Bulk Enrolment":

* Enrolment plugin -- choices are [ Manual Enrolments | Guest access | Self Enrolment | Cohort sync | Course meta link | Flat file CSV ]

* Role -- choices are [ Manager | Course creator | Professor | Non-editing professor | Student | Guest | Authenticated User | Authenticated user on frontpage | Academic Vice President | College Dean | Department Chair ]

The following is also in our Dashboard / Site administration / Plugins / Enrolments / Manage enrol plugins:

![image](https://user-images.githubusercontent.com/66813508/84872689-c8f01300-b0b4-11ea-9362-91a03c9edf28.png)

**Comment by abias** [comment]
I think the solution to your problem is already documented in https://github.com/moodleuulm/moodle-local_bulkenrol#localbulkenrolenrolusers: You most probably did not grant the necessary capability to your teachers / faculty. Please double-check this.

If the capability does not solve your problem, I am happy to discuss this problem further with you.

**Comment by rub-moodle-its** [comment]
Hey Alex,

we encountered the same issue upon installing this plugin on Moodle 3.7 - permissions are set, "User bulk enrolment" does show up on the Plugins page of Website Administration, but not under "Manage enrol plugins". However, there is no option to enrol users in bulk in the course administration menu.

Checking different themes and languages made no difference, either.
Plugin version: 2019081200
Release: v3.7-r1

Cheers
Thorsten
