### ISSUE TITLE
enrol users by username

### ISSUE THREAD

**Issue by Marx1st** [moodleuulm/moodle-local_bulkenrol#18]
Hi!

It would be great if usernames could be used to enrol users, too.

**Comment by abias** [comment]
Hi @Marx1st ,

thank you for this issue. 
This request would be fulfilled by the PR in #14.
Unfortunately, the review of this PR got stuck on our side as maintainers due to limited resources.

Feel free to test the patch from #14 and share your experience there.

Cheers,
Alex
