### ISSUE TITLE
should privacy class be using polyfill?

### ISSUE THREAD

**Issue by danmarsden** [moodleuulm/moodle-local_bulkenrol#4]
It looks like you only have a single branch here in github but your plugins db entry has versions for 3.3/3.4 as well. If you plan to support 3.3 on the master branch you may need to implement the polyfill:
https://docs.moodle.org/dev/Privacy_API#Difference_between_Moodle_3.3_and_more_recent_versions

If you don't plan to support 3.3 - feel free to close this as won't fix :-)

**Comment by abias** [comment]
Hi Dan,

I finally found the time to polish this plugin for plugin repo approval.
Thanks for this hint.

We have built this plugin for 3.2 and have uploaded some 3.2 versions to the plugin repo, but they are all invisible now and the version which you will finally approve won't be available for version older than 3.4 according to our Moodle release support strategy (https://github.com/moodleuulm/moodle-local_bulkenrol#moodle-release-support).

Thus, no need to implement the polyfill.

Cheers,
Alex
