### ISSUE TITLE
PARAM_RAW used when it looks like PARAM_ALPHANUMEXT should be used?

### ISSUE THREAD

**Issue by danmarsden** [moodleuulm/moodle-local_bulkenrol#5]
https://github.com/moodleuulm/moodle-local_bulkenrol/blob/master/index.php#L35

ideally would be good to be more restrictive on that param - it looks like it's supposed to be courseid_timetamp so PARAM_RAW isn't quite right?

**Comment by abias** [comment]
Hi Dan,

I finally found the time to polish this plugin for plugin repo approval.
Thanks for this hint.

I agree that this should be more restrictive. While the use of the key param (which the original developer of the plugin created) is somehow obscure to me, I have changed it to PARAM_ALPHANUMEXT now in 84002a6b3cd7e0bc6eb849e7bb044d1e06593939.

Cheers,
Alex
